import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/footer";
import { TabProvider } from "@/context/pagecontext";
import { SearchProvider } from "@/context/filterContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RentKro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SearchProvider>
          <TabProvider>
            <NavBar />
            {children}
            <Footer></Footer>
          </TabProvider>
        </SearchProvider>
      </body>
    </html>
  );
}
